Amnesty-International-France/website

wp-content/themes/espace-donateur/functions.php, wp-content/themes/espace-donateur/includes/admin/restrict-access.php, wp-content/themes/espace-donateur/includes/child-theme/configure.php, wp-content/themes/espace-donateur/includes/sales-force/authentification.php, wp-content/themes/espace-donateur/includes/sales-force/user-data.php, wp-content/themes/espace-donateur/templates/home.php, wp-content/themes/espace-donateur/templates/login-user.php
- Permet aux utilisateurs de se connecter et d'accéder aux pages reservées aux personnes ayant un compte
- désactive l'accès à l'espace admin aux personnes n'ayant pas le rôle d'administrateur
=> feat: a user can have a session

wp-content/plugins/aif-donor-space/includes/sales-force/authentification.php, wp-content/plugins/aif-donor-space/templates/create-account.php
- add a missing env var
- fix the create user form
=> fix: add missing env var + fix create account form

wp-content/plugins/aif-donor-space/templates/2FA-verification.php, wp-content/plugins/aif-donor-space/templates/check-email.php, wp-content/plugins/aif-donor-space/templates/create-account.php, wp-content/plugins/aif-donor-space/templates/login-user.php
- improves input sanitization for all forms
=> chore:  sanitize input

wp-content/plugins/aif-donor-space/aif-donor-space.php, wp-content/plugins/aif-donor-space/assets/js/create-duplicate-tax-receipt-demand.js, wp-content/plugins/aif-donor-space/includes/domain/2FA/index.php, wp-content/plugins/aif-donor-space/templates/2FA-verification.php, wp-content/plugins/aif-donor-space/templates/create-account.php, wp-content/plugins/aif-donor-space/templates/login-user.php
-  allows a user to receive a new 2FA code.
=> feat: get a new 2FA code

.gitignore, wp-content/plugins/aif-donor-space/aif-donor-space.php, wp-content/plugins/aif-donor-space/assets/css/style.css, wp-content/plugins/aif-donor-space/includes/domain/user-authentification.php, wp-content/plugins/aif-donor-space/includes/sales-force/user-data.php, wp-content/plugins/aif-donor-space/templates/forgotten-password.php, wp-content/plugins/aif-donor-space/templates/home.php, wp-content/plugins/aif-donor-space/templates/login-user.php, wp-content/plugins/aif-donor-space/templates/partials/alert.php, wp-content/plugins/aif-donor-space/templates/reset-password.php
#This PR :
- allow a user to reset his email if forgotten
=> feat: reset email

private/src/styles/pages/article/_featured-image.scss, private/src/styles/pages/article/type/_actuality.scss, private/src/styles/pages/article/type/_chronicle.scss, wp-content/themes/humanity-theme/patterns/post-metadata.php
Reverts Amnesty-International-France/website#142
=> Revert "fix actuality alignment"

wp-content/themes/humanity-theme/partials/article-card.php
=> remove landmark category from chip category into article card

wp-content/themes/humanity-theme/includes/admin/landmarks-settings.php, wp-content/themes/humanity-theme/patterns/archive-loop.php
=> remove featured landmarks from the main query on archive page

infogerance/aif-clever-cloud.php
pass jetpack in offline mode on staging
=> pass jetpack in offline mode on staging

private/src/scripts/blocks.js, private/src/scripts/editor/blocks/actions-homepage/EditComponent.jsx, private/src/scripts/editor/blocks/actions-homepage/index.jsx, private/src/styles/app.scss, private/src/styles/blocks/actions-homepage/_main.scss, private/src/styles/editor.scss, private/src/styles/gutenberg.scss, private/src/styles/pages/page/_base.scss, wp-content/themes/humanity-theme/includes/blocks/actions-homepage/register.php, wp-content/themes/humanity-theme/includes/blocks/actions-homepage/render.php, wp-content/themes/humanity-theme/includes/blocks/register.php, wp-content/themes/humanity-theme/includes/helpers/blocks.php
Depends on #[227 ](https://github.com/Amnesty-International-France/website/pull/227)
Don't merge before the first one.
=> homepage actions block

private/src/styles/pages/_page.scss, wp-content/themes/humanity-theme/templates/page-donation.html
create template donation page and this style sheet
=> Feat - Page DON template

private/src/scripts/modules/navigation.js, private/src/styles/components/_donation_calculator.scss, private/src/styles/layout/header/shared/_base.scss, wp-content/themes/humanity-theme/includes/blocks/donation-calculator/register.php, wp-content/themes/humanity-theme/includes/blocks/donation-calculator/render.php, wp-content/themes/humanity-theme/partials/donation-calculator.php, wp-content/themes/humanity-theme/partials/navigation/desktop.php
added donation calculator on menu
=> Feat - Donation calculator menu

private/src/scripts/App.js, private/src/scripts/modules/urgent-banner.js, private/src/static/images/icon-cross.svg, private/src/styles/app.scss, private/src/styles/layout/_urgent-banner.scss, wp-content/themes/humanity-theme/partials/navigation/desktop.php, wp-content/themes/humanity-theme/partials/urgent-banner.php
[Mise en place du bandeau urgent](https://linear.app/les-tilleuls/issue/AMN-268)
=> Feat - Mise en place du bandeau urgent

private/src/styles/pages/article/type/_petition.scss, wp-content/themes/humanity-theme/includes/petitions/create-petition.php, wp-content/themes/humanity-theme/includes/petitions/tables.php, wp-content/themes/humanity-theme/includes/post-types/petitions.php, wp-content/themes/humanity-theme/patterns/aside-petition-sticky.php, wp-content/themes/humanity-theme/patterns/petition-content.php
wp option delete aif_tables_created
=> feat: action soutien form

private/src/scripts/editor/blocks/link-icon/EditComponent.jsx, private/src/scripts/editor/blocks/link-icon/SaveComponent.jsx, private/src/scripts/editor/blocks/link-icon/index.jsx
https://linear.app/les-tilleuls/issue/AMN-277
=> add displayButton option for link icon block

wp-content/plugins/prismic-migration/blocks/slices/ListeDocumentsMapper.php, wp-content/themes/humanity-theme/includes/blocks/related-posts/render.php, wp-content/themes/humanity-theme/includes/theme-setup/acf.php, wp-content/themes/humanity-theme/patterns/page-content.php
https://linear.app/les-tilleuls/issue/AMN-272
=> fix: amn-272

private/src/scripts/editor/blocks/section-home/EditComponent.jsx, private/src/styles/blocks/section-home/_main.scss
https://linear.app/les-tilleuls/issue/AMN-288
=> add grey lighter color for section home block

private/src/scripts/editor/blocks/section-home/EditComponent.jsx, private/src/scripts/editor/blocks/section-home/SaveComponent.jsx, private/src/scripts/editor/blocks/section-home/index.jsx, private/src/styles/blocks/section-home/_main.scss
https://linear.app/les-tilleuls/issue/AMN-279
=> description and caption displayed for home section block

wp-content/themes/humanity-theme/partials/navigation/desktop.php
=> JetPack Search

private/src/styles/pages/_article.scss, private/src/styles/pages/article/type/_press-release.scss, wp-content/themes/humanity-theme/templates/single-press-release.html
[COMMUNIQUÉS PRESSE - page single](https://linear.app/les-tilleuls/issue/AMN-326)
=> Press release single

private/src/scripts/editor/blocks/card-image-text/EditComponent.jsx, wp-content/themes/humanity-theme/includes/blocks/card-image-text/render.php
https://linear.app/les-tilleuls/issue/AMN-325
=> add page choice and blank link for custom card

private/src/scripts/App.js, private/src/scripts/modules/donation-calculator.js, private/src/scripts/modules/navigation.js, private/src/styles/layout/header/shared/_base.scss, wp-content/themes/humanity-theme/partials/navigation/desktop.php
=> Fix - JetPack Search with Calculator

wp-content/themes/humanity-theme/includes/post-types/trainings.php
blocked access if not admin or subscriber onr private formation
=> Fix - Private formation

wp-content/themes/humanity-theme/patterns/page-content.php
https://linear.app/les-tilleuls/issue/AMN-266
=> fix: amn-266

private/src/styles/pages/article/type/_petition.scss
https://linear.app/les-tilleuls/issue/AMN-380
=> fix: amn-380

wp-content/themes/humanity-theme/patterns/petition-content.php
https://linear.app/les-tilleuls/issue/AMN-379
=> fix: amn-379

wp-content/themes/humanity-theme/includes/post-types/petitions.php
https://linear.app/les-tilleuls/issue/AMN-377
=> fix: amn-377

private/src/scripts/App.js, private/src/scripts/modules/page-menu.js, private/src/styles/app.scss, private/src/styles/pages/page/_page-menu.scss, private/src/styles/pages/page/type/_fondation.scss
fix error & anchor menu in sticky
=> Fix fondation

wp-content/themes/humanity-theme/partials/forms/taxonomy-filters.php
https://linear.app/les-tilleuls/issue/AMN-374
=> remove keyword filter for petition archive

wp-content/themes/humanity-theme/partials/archive/filters.php
https://linear.app/les-tilleuls/issue/AMN-234
=> remove feedzy filters from archives

wp-content/themes/humanity-theme/partials/article-card.php
https://linear.app/les-tilleuls/issue/AMN-375
=> article terms are now links

wp-content/themes/humanity-theme/functions.php, wp-content/themes/humanity-theme/includes/admin/trainings-settings.php, wp-content/themes/humanity-theme/patterns/archive-chapo.php
https://linear.app/les-tilleuls/issue/AMN-370
=> add settings for trainings archive

private/src/styles/pages/page/type/_standard.scss, wp-content/themes/humanity-theme/patterns/page-content.php, wp-content/themes/humanity-theme/patterns/page-hero.php
https://linear.app/les-tilleuls/issue/AMN-387
=> fix hero for standard page without featured img

wp-content/themes/humanity-theme/patterns/petition-thanks.php
https://linear.app/les-tilleuls/issue/AMN-382
=> fix share links for petition

wp-content/themes/humanity-theme/includes/post-types/pop-in.php, wp-content/themes/humanity-theme/includes/theme-setup/acf.php
* remove Gutenberg mode
* added ACF
[BO - Retirer le mode d'édition Gutenberg](https://linear.app/les-tilleuls/issue/AMN-410)
=> Feat - Variantes Popin without Gutenberg

wp-content/themes/humanity-theme/includes/seo/opengraph.php
https://linear.app/les-tilleuls/issue/AMN-405
=> add default img in og:image when featured image is empty

private/src/scripts/App.js, private/src/scripts/modules/back-to-top.js, private/src/static/images/icon-simple-arrow.svg, private/src/styles/app.scss, private/src/styles/components/_back-to-top.scss, wp-content/themes/humanity-theme/patterns/footer-content.php
button back to top
[Toutes pages - remontée haut de page](https://linear.app/les-tilleuls/issue/AMN-153)
=> Feat  - Back To Top

private/src/scripts/editor/blocks/section-home/EditComponent.jsx, private/src/scripts/editor/blocks/section-home/SaveComponent.jsx, private/src/styles/blocks/section-home/_main.scss
https://linear.app/les-tilleuls/issue/AMN-433
=> section home block : page link on icons

private/src/scripts/admin.js, private/src/scripts/admin/components/IconPickerControl.jsx, private/src/scripts/editor/blocks/link-icon/EditComponent.jsx, private/src/styles/admin.scss, private/src/styles/admin/_icon-picker-control.scss
=> fix(link block icons): #amn-427 display icons for a better experience

private/src/scripts/editor/blocks/section-home/EditComponent.jsx, private/src/scripts/editor/blocks/section-home/index.jsx
https://linear.app/les-tilleuls/issue/AMN-431
=> add choice link on section home button

wp-content/themes/humanity-theme/functions.php, wp-content/themes/humanity-theme/includes/petitions/tables.php, wp-content/themes/humanity-theme/includes/salesforce/authentification.php, wp-content/themes/humanity-theme/includes/salesforce/data.php, wp-content/themes/humanity-theme/includes/salesforce/user.php, wp-content/themes/humanity-theme/includes/urgent-action/rest-endpoint.php, wp-content/themes/humanity-theme/includes/urgent-action/syncs.php, wp-content/themes/humanity-theme/includes/urgent-action/tables.php, wp-content/themes/humanity-theme/patterns/aside-register-activist-sticky.php, wp-content/themes/humanity-theme/patterns/aside-urgent-register-huma-sticky.php, wp-content/themes/humanity-theme/patterns/aside-urgent-register-sms-sticky.php, wp-content/themes/humanity-theme/patterns/aside-urgent-register-sticky.php
[Connecter chaque formulaire à son objet Salesforce](https://linear.app/les-tilleuls/issue/AMN-341)
=> Feat - Salesforce Register UA & Militant

private/src/scripts/editor/blocks/card-image-text/EditComponent.jsx
https://linear.app/les-tilleuls/issue/AMN-454
=> remove link into gutenberg for card image text block

wp-content/themes/humanity-theme/patterns/aside-donation-sticky.php
https://linear.app/les-tilleuls/issue/AMN-471
=> fix calculator for donation page

wp-content/plugins/prismic-migration/RepairLinksCli.php, wp-content/plugins/prismic-migration/utils/LinksUtils.php
https://linear.app/les-tilleuls/issue/AMN-476
Relancer wp repair-links
=> fix: amn-476

wp-content/themes/humanity-theme/patterns/404.php
=> link in 404 page

private/src/scripts/modules/donation-calculator.js
https://linear.app/les-tilleuls/issue/AMN-529
=> fix calculator

wp-content/themes/humanity-theme/partials/navigation/desktop.php
https://linear.app/les-tilleuls/issue/AMN-544
=> target blank on my space navbar button

private/src/styles/blocks/training-card/_main.scss, wp-content/themes/humanity-theme/partials/training-card.php
https://linear.app/les-tilleuls/issue/AMN-443
=> improve training card

wp-content/themes/humanity-theme/includes/post-types/petitions.php
https://linear.app/les-tilleuls/issue/AMN-372
=> display petition by date
